### ISSUE TITLE
[BUG] Tabsbar doesn't have separator between tabs

### ISSUE THREAD

**Issue by AdamXweb** [AdamXweb/WhiteSurFirefoxThemeMacOS#117]
### Describe the problem

In comparison to Safari, the theme doesn't have a separator between each tab.
See examples
<img width="764" alt="Screenshot 2024-04-14 at 7 04 17 PM" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/d5ca6a1e-48dc-4cae-910c-c088f49597e7">
<img width="790" alt="Screenshot 2024-04-14 at 7 03 49 PM" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/8c979bb6-c27d-4c14-aa33-a69bd82a8da5">

### Version

1.5.4

### OS

MacOS 14

### Firefox Version

124

### Install Options

n/a

### Colour Theme

n/a

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/4665c5b6e03127597c7cf99d91b676c9d1fca95d/chrome/WhiteSur/parts/tabsbar.css#L63

**Comment by amcottre** [comment]
Apologies to comment on an old issue but how do I add separators? I've tried removing this section of code and changing the values but nothing works

**Comment by amcottre** [comment]
Apologies to comment on an old issue but is there a way to add the separators back in or is it just how this theme is built? I've tried changing the code in that section but nothing is working for me

**Comment by AdamXweb** [comment]
Hi @amcottre ,

It's something on the to-do list, however I haven't had time to make it just right. In the meantime you could try tweaking something like this on
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/4665c5b6e03127597c7cf99d91b676c9d1fca95d/chrome/WhiteSur/parts/tabsbar.css#L410-L414

```css
	.tab-background {
		border-radius: 0 !important;
		margin-block: 0 !important;
		box-shadow: inset 0px 0.8px 2px var(--gnome-inactive-toolbar-background), inset 0px -1px 0px 1px var(--gnome-inactive-toolbar-background) !important;
	}
``` 

Instead of a border around the tabs, the same effect is gained by creating an inset shadow.
